### ISSUE TITLE
gives error: mkdir()

### ISSUE THREAD

**Issue by yakshdeveloper** [swadmahfuz/Certificate-Verification-System#2]
When The first time I clone this project and get a error mkdir() in Import route at the same time I found the solution on the issue  'local_path'          => '/tmp', the change in the config/excel.php  and solve the issue.

**Comment by swadmahfuz** [comment]
I have been running this app on a Linux hosting but haven't faced this issue. Maybe this is persistent on local machines. Thanks for the issue and the corresponding solution! :)
