### ISSUE TITLE
Structure Issue

### ISSUE THREAD

**Issue by yakshdeveloper** [swadmahfuz/Certificate-Verification-System#3]
Image is not loading properly and date based search is missing one more think its required role based authentication

**Comment by swadmahfuz** [comment]
Are you running it on a local Windows machine? I modified the file paths to work on cPanel servers as the images were not loading properly after uploading it on a live server.

**Comment by yakshdeveloper** [comment]
Yes

**Comment by yakshdeveloper** [comment]
Route
 
Route::get('/bulkcertificatepdf',[CertificateController::class,'bulkcertificatepdf'])->name('bulkcertificatepdf');

// controler 

public function bulkcertificatepdf(Request $request)
    {

        $orderId = request('order_id');
        if (!empty($orderId)) {
            $orderIdArray = explode(',', $orderId);

            if (!empty($orderIdArray)) {

                $c = Certificate::whereIn('id', $orderIdArray)->get();
                // echo '<pre>'; print_r(  $c ); echo '</pre>';
                foreach ($c as $key => $certificate) {
                    $data = [
                        'title' => 'Welcome to ItSolutionStuff.com',
                        'date' => date('m/d/Y'),
                        'certificate' => $certificate,
                        'selected' => request('order_id')
                    ];

                    $view = view('myPDF', compact('certificate'));
                    $pdf = PDF::loadHTML($view->render())->setPaper('A4', 'landscape');
                    $filename = 'test' . $key . '.pdf';
                    $pdf->save($filename);
                    $files[] = $filename;

                    // echo '<pre>'; print_r( $filename ); echo '</pre>';

                }

                $zip = new ZipArchive();
                $zipFilename = 'certificates.zip';

                if ($zip->open($zipFilename, ZipArchive::CREATE) === TRUE) {
                    foreach ($files as $file) {
                        $zip->addFile($file);
                    }
                    $zip->close();
                    // Download the ZIP file
                    return response()->download($zipFilename)->deleteFileAfterSend();
                }
            }
        }
    }

// Dashboard blade

<input type="checkbox" value="{{$certificate->id}}"
                                                name="order_id[]"></th>

 <script>
        function downloadPDF() {

            var orderId = new Array();
            $.each($("input[name='order_id[]']:checked"), function() {
                $('#pdf_' + $(this).val()).html('Generated');
                orderId.push($(this).val());
                // console.log(orderId)
                // console.log(typeof(orderId))
            });

            if (orderId.length > 0) {
                $('#checkbox-error').html('');
                var url = "{{ url('bulkcertificatepdf') }}?order_id=" + orderId;
                window.location.href = url;
                $('input[name="order_id[]"]').prop('checked', false);
            } else {
                $('#checkbox-error').html('Select any one checkbox');

            }

        }
    </script>

**Comment by yakshdeveloper** [comment]
add dom pdf package
